name: 'Install npm modules'
description: 'Caches node_modules based on package-lock.json hash and installs dependencies if cache is not hit'
inputs:
  working-directory:
    description: 'The working directory for the action'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup variables for action
      id: vars
      shell: bash
      run: |
        pathHash="$(echo -n "${{ inputs.working-directory }}" | shasum -a 256 | awk '{ print $1 }')"
        lockHash="$(shasum -a 256 "${{ inputs.working-directory }}package-lock.json" | awk '{ print $1 }'))"
        modulesPath="${{ inputs.working-directory }}node_modules"

        echo "cache-key=${{ runner.os }} — $modulesPath — $lockHash" | tee -a "$GITHUB_OUTPUT"
        echo "modules-path=$modulesPath" | tee -a "$GITHUB_OUTPUT"
  
    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: ${{ steps.vars.outputs.modules-path }}
        key: ${{ steps.vars.outputs.cache-key }}

    - name: Install dependencies
      if: steps.restore-cache.outputs.cache-hit != 'true'
      shell: bash
      run: |
        if [ ! -z "${{ inputs.working-directory }}" ]; then
          cd "${{ inputs.working-directory }}"
        fi

        npm install

    - name: Save cache
      if: steps.restore-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: ${{ steps.vars.outputs.modules-path }}
        key: ${{ steps.vars.outputs.cache-key }}
