# Simple workflow for deploying static content to GitHub Pages
name: Test PR

on:
  # Runs on pushes targeting the default branch
  pull_request:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # Single deploy job since we're just deploying
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
          
      - name: Combine json
        run: "cd scripts && deno run ./combine.ts --skipHashes"

      - uses: actions/upload-artifact@v4.3.3
        with:
          # A file, directory or wildcard pattern that describes what to upload
          path: "./dist/mods.json"
