# Simple workflow for deploying static content to GitHub Pages
name: Update data from ComputerElite

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Every two hours
  schedule:
    - cron: "30 */2 * * *"

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  # Single deploy job since we're just deploying
  update-github-icons:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Update the mods.json from ComputerElite
        run: |
          wget "https://computerelite.github.io/tools/Beat_Saber/mods.json" -O website/public/mods.json
          cd scripts
          npm install
          npx tsx ./split.ts 2>&1
          npx tsx ./delete-discord-mods.ts 2>&1
          npx tsx ./update-github-icons.ts 2>&1
          npx tsx ./update-covers.ts 2>&1

      - name: Configure git user
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit the updated files
        run: |
          git add -A mods
          (
            git commit -m "Update mods" &&
            (
              echo "MODS_UPDATED=yes" >> $GITHUB_ENV
            )
          ) || true

      - name: Push the updated files
        if: env.MODS_UPDATED == 'yes'
        run: |
          git pull --rebase
          git push

      - name: Trigger deploy
        if: env.MODS_UPDATED == 'yes'
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{"event_type":"trigger_deploy"}'
